---
sidebar: sidebar 
permalink: task_grant_user_privileges.html 
keywords: grant, user, privileges, TACACS+, server, group, command, commands, access, CSA, user, account 
summary: 'Se si utilizza un server TACACS+ e si devono concedere privilegi utente CSA per gli switch, è necessario creare un gruppo di privilegi utente e concedere al gruppo l"accesso ai comandi di configurazione specifici richiesti da CSA.' 
---
= Concedere i privilegi dell'utente CSA utilizzando un server TACACS+
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si utilizza un server TACACS+ e si devono concedere privilegi utente CSA per gli switch, è necessario creare un gruppo di privilegi utente e concedere al gruppo l'accesso ai comandi di configurazione specifici richiesti da CSA. I seguenti comandi devono essere scritti nel file di configurazione del server TACACS+.

.Fasi
. Immettere quanto segue per creare un gruppo di privilegi utente con accesso di sola lettura: Group=nome_gruppo { default service=deny service=exec{ privv-lvl=0 } }
. Immettere quanto segue per consentire l'accesso ai comandi richiesti da CSA: cmd=show { permit "ambiente" permit "versione" permit "funzione" permit "set di funzioni" permit "running-config" permit "interfaccia" permit "interfaccia" permit "inventario" permit "licenza" permit "modulo" permit "port-channel database" permit "ntp peer" permit "utilizzo di licenze" permit "switch-config" permessi "0-tmtmttint" permessi "switch" permesso "cdp neighbor detail" permesso "vlan" permesso "vpc" permesso "vpc peer-keealive" permesso "mac address-table" permesso "lacp port-channel" permesso "policy-map" permesso "policy-map system type qos" permesso "policy-map system type network-qos" permesso "zoneset active" permesso "san-port-channel summary" permesso "database clogs" permesso "dettaglio database" dati" permesso "clogs" permesso "zoneset active" permesso "vsan" permesso "utilizzo vsan" permesso "appartenenza vsan" }
. Immettere quanto segue per aggiungere l'account utente CSA al gruppo appena creato: User=User_account{ member=group_name login=file/etc/passwd }

